"""User-provided SIG-ES reference catalog; not independently verified facts."""

ORGANIZATIONS = [
    {"id": 1, "nome": "SRA/ES", "sigla": "SRA"},
    {"id": 2, "nome": "CGU/ES", "sigla": "CGU"},
    {"id": 3, "nome": "FUNDACENTRO/ES", "sigla": "FUNDACENTRO"},
    {"id": 4, "nome": "PFN/ES", "sigla": "PFN"},
    {"id": 5, "nome": "ABIN/ES", "sigla": "ABIN"},
    {"id": 6, "nome": "DRF/ES", "sigla": "DRF"},
    {"id": 7, "nome": "SPU/ES", "sigla": "SPU"},
    {"id": 8, "nome": "SRT/ES", "sigla": "SRT"},
    {"id": 9, "nome": "AGU/ES", "sigla": "AGU"},
    {"id": 10, "nome": "IBGE/ES", "sigla": "IBGE"},
    {"id": 11, "nome": "CONTRATOS DTI", "sigla": "DTI"},
]

MATERIALS = [
    {"id": 1, "nome": "AÇÚCAR", "categoria": "Alimentos"},
    {"id": 2, "nome": "ALMOXARIFADO", "categoria": "Geral"},
    {"id": 3, "nome": "CAFÉ", "categoria": "Alimentos"},
    {"id": 4, "nome": "COMBUSTÍVEL", "categoria": "Frota"},
    {"id": 5, "nome": "GÁS", "categoria": "Geral"},
    {"id": 6, "nome": "TOTAL CONSUMO", "categoria": "Consolidado"},
]

SERVICES = [
    {"id": 1, "nome": "ÁGUA E ESGOTO - BRK - ART CACHOEIRO DE ITAPEMIRIM"},
    {"id": 2, "nome": "ÁGUA E ESGOTO - CESAN"},
    {"id": 3, "nome": "ÁGUA E ESGOTO - CESAN - ART PARQUE MOSCOSO"},
    {"id": 4, "nome": "ÁGUA E ESGOTO - CESAN - GUARAPARI"},
    {"id": 5, "nome": "ÁGUA E ESGOTO - CESAN - ART NOVA VENÉCIA"},
    {"id": 6, "nome": "ÁGUA E ESGOTO - SAAE - ART ALEGRE"},
    {"id": 7, "nome": "ÁGUA E ESGOTO - SAAE - ART ARACRUZ"},
    {"id": 8, "nome": "ÁGUA E ESGOTO - SAAE - ART LINHARES"},
    {"id": 9, "nome": "ÁGUA E ESGOTO - SAAE - ART SÃO MATEUS"},
    {"id": 10, "nome": "AVALIAÇÃO DE IMÓVEIS - SAFIRA - SILVA"},
    {"id": 11, "nome": "AVALIAÇÃO DE INSALUBRIDADE - RESULT"},
    {"id": 12, "nome": "CORREIOS - EBCT"},
    {"id": 13, "nome": "DEDETIZADORA"},
    {"id": 14, "nome": "ELEVADORES - MILÊNIO"},
    {"id": 15, "nome": "ENERGIA ELÉTRICA - EDP"},
    {"id": 16, "nome": "ENERGIA ELÉTRICA - EDP - ART ALEGRE"},
    {"id": 17, "nome": "ENERGIA ELÉTRICA - EDP - ART ARACRUZ"},
    {"id": 18, "nome": "ENERGIA ELÉTRICA - EDP - ART CACHOEIRO DE ITAPEMIRIM"},
    {"id": 19, "nome": "ENERGIA ELÉTRICA - EDP - ART GUARAPARI"},
    {"id": 20, "nome": "ENERGIA ELÉTRICA - EDP - ART LINHARES"},
    {"id": 21, "nome": "ENERGIA ELÉTRICA - EDP - ART NOVA VENÉCIA"},
    {"id": 22, "nome": "ENERGIA ELÉTRICA - EDP - ART SÃO MATEUS"},
    {"id": 23, "nome": "ENERGIA ELÉTRICA - EDP - ART VILA VELHA"},
    {"id": 24, "nome": "ENERGIA ELÉTRICA - EDP - ART VITÓRIA"},
    {"id": 25, "nome": "ENERGIA ELÉTRICA - LUZ E FORÇA SANTA MARIA"},
    {"id": 26, "nome": "IMPOSTOS E TAXAS - PMV - NÃO CONTRATOS"},
    {"id": 27, "nome": "JARDINAGEM - SUDESTE"},
    {"id": 28, "nome": "LIMPEZA - SUDESTE"},
    {"id": 29, "nome": "LOCAÇÃO DE IMÓVEL - ART ALEGRE"},
    {"id": 30, "nome": "LOCAÇÃO DE IMÓVEL - ART ARACRUZ"},
    {"id": 31, "nome": "LOCAÇÃO DE IMÓVEL - ART CACHOEIRO DE ITAPEMIRIM"},
    {"id": 32, "nome": "LOCAÇÃO DE IMÓVEL - ART COLATINA"},
    {"id": 33, "nome": "LOCAÇÃO DE IMÓVEL - ART LINHARES"},
    {"id": 34, "nome": "LOCAÇÃO DE IMÓVEL - ART VILA VELHA"},
    {"id": 35, "nome": "LOCAÇÃO SCANNER - PFN - ALLGED"},
    {"id": 36, "nome": "MANUTENÇÃO CENTRAL DE ALARME - PREVIEW"},
    {"id": 37, "nome": "MANUTENÇÃO CIVIL e AR - PGE"},
    {"id": 38, "nome": "MANUTENÇÃO DE VEÍCULOS - XP3 - HALF"},
    {"id": 39, "nome": "MANUTENÇÃO TELEFONIA - ROTACIONAL - DND"},
    {"id": 40, "nome": "MANUTENÇÃO VÍDEO-MONITORAMENTO - PREVIEW"},
    {"id": 41, "nome": "PUBLICIDADE - I.N. E EBC"},
    {"id": 42, "nome": "TELEFONIA FIXA E MÓVEL - VIVO - JCA"},
    {"id": 43, "nome": "TERCEIRIZAÇÃO - MÁXIMA"},
    {"id": 44, "nome": "VIGILÂNCIA - SEI VIGILÂNCIA E SEGURANÇA LTDA"},
    {"id": 45, "nome": "VIGILÂNCIA ELETRÔNICA - AGUIAR & MANTOVANI LTDA"},
]

SUPPLIERS = [
    {"id": 1, "nome": "BRK", "servico_associado": "ÁGUA E ESGOTO - BRK - ART CACHOEIRO DE ITAPEMIRIM"},
    {"id": 2, "nome": "CESAN", "servico_associado": "ÁGUA E ESGOTO - CESAN"},
    {"id": 3, "nome": "SAAE", "servico_associado": "ÁGUA E ESGOTO - SAAE - ART ALEGRE"},
    {"id": 4, "nome": "SAFIRA", "servico_associado": "AVALIAÇÃO DE IMÓVEIS - SAFIRA - SILVA"},
    {"id": 5, "nome": "SILVA", "servico_associado": "AVALIAÇÃO DE IMÓVEIS - SAFIRA - SILVA"},
    {"id": 6, "nome": "RESULT", "servico_associado": "AVALIAÇÃO DE INSALUBRIDADE - RESULT"},
    {"id": 7, "nome": "EBCT", "servico_associado": "CORREIOS - EBCT"},
    {"id": 8, "nome": "MILÊNIO", "servico_associado": "ELEVADORES - MILÊNIO"},
    {"id": 9, "nome": "EDP", "servico_associado": "ENERGIA ELÉTRICA - EDP"},
    {"id": 10, "nome": "LUZ E FORÇA SANTA MARIA", "servico_associado": "ENERGIA ELÉTRICA - LUZ E FORÇA SANTA MARIA"},
    {"id": 11, "nome": "PMV", "servico_associado": "IMPOSTOS E TAXAS - PMV - NÃO CONTRATOS"},
    {"id": 12, "nome": "SUDESTE", "servico_associado": "JARDINAGEM - SUDESTE / LIMPEZA - SUDESTE"},
    {"id": 13, "nome": "ALLGED", "servico_associado": "LOCAÇÃO SCANNER - PFN - ALLGED"},
    {"id": 14, "nome": "PREVIEW", "servico_associado": "MANUTENÇÃO CENTRAL DE ALARME - PREVIEW / MANUTENÇÃO VÍDEO-MONITORAMENTO - PREVIEW"},
    {"id": 15, "nome": "PGE", "servico_associado": "MANUTENÇÃO CIVIL e AR - PGE"},
    {"id": 16, "nome": "XP3 - HALF", "servico_associado": "MANUTENÇÃO DE VEÍCULOS - XP3 - HALF"},
    {"id": 17, "nome": "DND", "servico_associado": "MANUTENÇÃO TELEFONIA - ROTACIONAL - DND"},
    {"id": 18, "nome": "I.N. E EBC", "servico_associado": "PUBLICIDADE - I.N. E EBC"},
    {"id": 19, "nome": "VIVO - JCA", "servico_associado": "TELEFONIA FIXA E MÓVEL - VIVO - JCA"},
    {"id": 20, "nome": "MÁXIMA", "servico_associado": "TERCEIRIZAÇÃO - MÁXIMA"},
    {"id": 21, "nome": "SEI VIGILÂNCIA E SEGURANÇA LTDA", "servico_associado": "VIGILÂNCIA - SEI VIGILÂNCIA E SEGURANÇA LTDA"},
    {"id": 22, "nome": "AGUIAR & MANTOVANI LTDA", "servico_associado": "VIGILÂNCIA ELETRÔNICA - AGUIAR & MANTOVANI LTDA"},
]

CATALOG_SOURCE = "referencia_fornecida_pelo_usuario"
CATALOG_VERIFIED = False
